# Generated by Django 4.2.7 on 2024-03-05 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_alter_applications_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='saved_jobs',
            field=models.ManyToManyField(blank=True, null=True, related_name='saved', to='myapp.jobs'),
        ),
    ]
